#!/bin/sh

trap 'tput rmcup; tput cnorm; exit 1' INT QUIT TERM HUP

esc="\033"
reset="${esc}[0m"
redf="${esc}[31m"
cyanf="${esc}[36m"
purplef="${esc}[35m"

core() {
	DATE=$(date '+%H:%M:%S %d.%m.%Y')
	DESKTOP_ID=$(xprop -root 32c '\t$0' _NET_CURRENT_DESKTOP | cut -f 2)
    GAMMA=$(xgamma)
	NAME=${LOGNAME}
	MEM=$(top -n | grep Memory | awk {'print $6'})
	SSID=$(ifconfig | grep join | sed -e 's/.*join\(.*\)chan.*/\1/')
	IIP=$(ifconfig | awk '/^[a-z0-9]+:/ {iface=$1; sub(/:$/, "", iface)} $1 == "inet" {print iface ":" $2}')
	BATTERY=$(apm)
}

tput smcup
tput civis

while true; do
    core

    BUFFER="[${cyanf}${DATE}${reset}]\n"
    BUFFER="${BUFFER}${cyanf}Desktop:${reset} [${DESKTOP_ID}][${GAMMA}]\n"
    BUFFER="${BUFFER}${cyanf}User:${reset} ${NAME}\n"
    BUFFER="${BUFFER}${cyanf}Memory:${reset} ${MEM}\n"
    BUFFER="${BUFFER}${cyanf}Wi-Fi:${reset} ${SSID:-NONE}\n"
    BUFFER="${BUFFER}${cyanf}IP:${reset}\n${IIP:-down}\n"
    BUFFER="${BUFFER}${cyanf}Battery:${reset}\n${BATTERY}"

    tput cup 0 0
    
	printf "%b" "$BUFFER"

    sleep 1
done